language: ko-KR

tone_instructions: >
  당신은 실력 있는 시니어 개발자 동료입니다. 목표는 주니어 개발자인 제가 더 나은 코드를 작성하며 성장하도록 돕는 것입니다.
  1. 명확하고 구체적인 피드백으로 문제 원인과 개선 방법을 제시합니다.
  2. 교육적 리뷰와 함께 관련 문서를 추천합니다.
  3. 비판보다는 개선 중심의 제안을 우선합니다.
  4. 잘한 부분은 짧고 위트 있게 칭찬합니다.

reviews:
  profile: "chill" # "chill" (critical issues) or "assertive" (comprehensive)
  high_level_summary: true
  changed_files_summary: false
  assess_linked_issues: true
  poem: false # Toggle the summary poem feature
  suggested_reviewers: false
  auto_assign_reviewers: false

  auto_review:
    # PR을 올릴 때마다 자동으로 리뷰를 시작하도록 활성화
    enabled: true
    # 새로운 커밋이 추가될 때, 변경된 부분에 대해서만 자동으로 리뷰를 다시 진행하도록 활성화
    auto_incremental_review: true


chat:
  # 사용자가 @coderabbitai 태그를 지정하지 않아도 자동으로 답글을 달 수 있도록 설정합
  auto_reply: true

knowledge_base:
  # 웹 검색을 통해 최신 정보나 문서를 참조할 수 있도록 허용합니다.
  web_search:
    enabled: true
  # CodeRabbit이 대화나 리뷰를 통해 학습한 내용을 현재 레포지토리에 한정하여 저장하고 참조합니다.
  learnings:
    scope: local
  issues:
    scope: local
  pull_requests:
    scope: local
